### ISSUE TITLE
import AuthProvider question

### ISSUE THREAD

**Issue by hydrohiester** [PropelAuth/documentation#35]
https://github.com/PropelAuth/documentation/blob/a40e6f14b7a82cef3d9864ea2b560a0f725417df/getting-started/nextjs.mdx#L69

Is this the client-side `AuthProvider` imported from @propelauth/react ?

**Comment by andrew-propelauth** [comment]
Thanks for flagging; we just updated the docs to add the import as well:
https://github.com/PropelAuth/documentation/commit/577f59e21f824c9bb1cd93172ffbe59b93380bae

The AuthProvider is in `@propelauth/nextjs/client` not from `@propelauth/react`.

**Comment by hydrohiester** [comment]
Does this also export a `RequiredAuthProvider`?

**Comment by andrew-propelauth** [comment]
We didn't add a `RequiredAuthProvider` equivalent because in the AppRouter you can just add:

```
getUserOrRedirect()
```

to a Layout and it ends up doing the same thing but is done on the server vs the client. Does that work for you?

**Comment by hydrohiester** [comment]
Do I have to add that to every page I want to protect?

From: andrew-propelauth ***@***.***>
Date: Wednesday, July 5, 2023 at 1:06 PM
To: PropelAuth/documentation ***@***.***>
Cc: Chris Hiester ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL]Re: [PropelAuth/documentation] import AuthProvider question (Issue #35)

We didn't add a RequiredAuthProvider equivalent because in the AppRouter you can just add:

getUserOrRedirect()

to a Layout and it ends up doing the same thing but is done on the server vs the client. Does that work for you?

**Comment by andrew-propelauth** [comment]
You don't have to do it on every page that you want to protect. You can, for example, place it in `app/layout.tsx` and it would apply to every page that uses the App Router, since they would all use that layout. Placing it in `app/admin/layout.tsx` would apply to every route underneath `/admin`
