### ISSUE TITLE
Do I create this directory

### ISSUE THREAD

**Issue by hydrohiester** [PropelAuth/documentation#36]
https://github.com/PropelAuth/documentation/blob/a40e6f14b7a82cef3d9864ea2b560a0f725417df/getting-started/nextjs.mdx#L49C1-L49C1

if my app doesn' t have `/app/api/auth/[slug], do I have to create it?

**Comment by andrew-propelauth** [comment]
Yes, you'll need to create it and add that file.

**Comment by hydrohiester** [comment]
OK, but what does it do? 

What if my api route is something like `/app/search/route.ts` and isn't in `/app/api/[...]`

**Comment by andrew-propelauth** [comment]
Ah - answered it separately here: https://github.com/PropelAuth/documentation/issues/38#issuecomment-1622147084

These are API routes that we use to manage authentication for your users. Right now, the library expects it to be at `/api/auth/*`. It manages updating the user's information, logging out and clearing cookies, etc.

**Comment by hydrohiester** [comment]
Use of the `/src` directory is optional, so these docs might be misleading to anyone using NextJS 13 without it.
