### ISSUE TITLE
use client required?

### ISSUE THREAD

**Issue by hydrohiester** [PropelAuth/documentation#37]
https://github.com/PropelAuth/documentation/blob/a40e6f14b7a82cef3d9864ea2b560a0f725417df/getting-started/nextjs.mdx#L75

Since this is a React Context, doesn't it require `use client` on NextJS 13?

**Comment by andrew-propelauth** [comment]
The AuthProvider in `@propelauth/nextjs/client` does have "use client" in it and should work out of the box in NextJS 13.
