### ISSUE TITLE
Detail needed on setting up routes

### ISSUE THREAD

**Issue by hydrohiester** [PropelAuth/documentation#38]
https://github.com/PropelAuth/documentation/blob/a40e6f14b7a82cef3d9864ea2b560a0f725417df/getting-started/nextjs.mdx#L47

What is the purpose of doing this?

**Comment by andrew-propelauth** [comment]
Those routes manage the authentication information. They take care of things like logging out and clearing any cookies associated with the user, or redirecting the user to the login/signup pages properly.
